WITH
Empresa AS (
    SELECT
        CODEMP,
        NVL(WMSLOCALAJEST, (SELECT INTEIRO FROM TSIPAR WHERE CHAVE = 'WMSLOCALAJEST')) AS CODLOCAL_AJUSTE
    FROM TGFEMP
    WHERE CODEMP = 7
),
EstoqueComercial AS (
    SELECT
        EST.CODPROD,
        SUM(NVL(EST.ESTOQUE, 0)) AS ESTOQUE
    FROM TGFEST EST
    CROSS JOIN Empresa
    WHERE EST.CODEMP = Empresa.CODEMP
      AND EST.CODLOCAL = Empresa.CODLOCAL_AJUSTE
    GROUP BY EST.CODPROD
)
SELECT
    EST.CODPROD,
    PRO.DESCRPROD,
    EST.ESTOQUE
FROM EstoqueComercial EST
LEFT JOIN TGFPRO PRO ON PRO.CODPROD = EST.CODPROD
WHERE ROWNUM <= 10
