-- ================================================================================
-- QUERY V4 - RELATORIO CONSOLIDADO POR PRODUTO
-- ================================================================================
-- Retorna 1 linha por produto com os mesmos calculos da analise detalhada
-- Mostra apenas produtos com divergencia entre ERP e WMS
-- ================================================================================

WITH
Empresa AS (
    SELECT
        CODEMP,
        NVL(WMSLOCALAJEST, (SELECT INTEIRO FROM TSIPAR WHERE CHAVE = 'WMSLOCALAJEST')) AS CODLOCAL_AJUSTE
    FROM TGFEMP
    WHERE CODEMP = 7  -- Parametro: empresa
),
SaldoWmsTela AS (
    SELECT
        ESTW.CODPROD,
        SUM(NVL(ESTW.ESTOQUEVOLPAD - ESTW.SAIDPENDVOLPAD, 0)) AS SALDO_WMS_TELA
    FROM TGWEST ESTW
    JOIN TGWEND WEND ON WEND.CODEND = ESTW.CODEND
    JOIN TGFEMP EMP ON EMP.CODEMP = WEND.CODEMP
    CROSS JOIN Empresa
    WHERE EMP.CODEMP = Empresa.CODEMP
      AND EMP.UTILIZAWMS = 'S'
      AND WEND.BLOQUEADO = 'N'
      AND WEND.EXCLCONF = 'N'
      AND NOT EXISTS (
            SELECT 1 FROM TGWDCA DCA
            WHERE DCA.TIPDOCA = 'S' AND DCA.CODEND = WEND.CODEND
      )
      AND ESTW.CONTROLE <> '#EXPLOTESEP'
      AND NVL(EMP.WMSLOCALAJEST, (SELECT INTEIRO FROM TSIPAR WHERE CHAVE = 'WMSLOCALAJEST')) = Empresa.CODLOCAL_AJUSTE
    GROUP BY ESTW.CODPROD
),
PedidosPendentes AS (
    SELECT
        ITE.CODPROD,
        SUM(NVL(ITE.QTDNEG, 0)) AS QTD_PEDIDO_PENDENTE
    FROM TGFITE ITE
    JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
    CROSS JOIN Empresa
    WHERE CAB.CODEMP = Empresa.CODEMP
      AND CAB.CODTIPOPER IN (1007, 1017, 1018, 1019, 1020, 1023, 1024, 1025)
      AND CAB.PENDENTE = 'S'
      AND CAB.STATUSNOTA = 'L'
    GROUP BY ITE.CODPROD
),
EstoqueComercial AS (
    SELECT
        EST.CODPROD,
        SUM(NVL(EST.ESTOQUE, 0)) AS ESTOQUE,
        SUM(NVL(EST.RESERVADO, 0)) AS RESERVADO,
        SUM(NVL(EST.WMSBLOQUEADO, 0)) AS WMSBLOQUEADO
    FROM TGFEST EST
    CROSS JOIN Empresa
    WHERE EST.CODEMP = Empresa.CODEMP
      AND EST.CODLOCAL = Empresa.CODLOCAL_AJUSTE
    GROUP BY EST.CODPROD
)
SELECT * FROM (
    SELECT
        7 AS CODEMP,
        EST.CODPROD,
        PRO.DESCRPROD,
        PRO.REFERENCIA,
        EST.ESTOQUE,
        EST.RESERVADO,
        EST.WMSBLOQUEADO,
        (EST.ESTOQUE - EST.RESERVADO - EST.WMSBLOQUEADO) AS DISPONIVEL_COMERCIAL,
        NVL(WMS.SALDO_WMS_TELA, 0) AS SALDO_WMS_TELA,
        NVL(PED.QTD_PEDIDO_PENDENTE, 0) AS QTD_PEDIDO_PENDENTE,
        GREATEST(NVL(WMS.SALDO_WMS_TELA, 0) - NVL(PED.QTD_PEDIDO_PENDENTE, 0), 0) AS WMS_APOS_PEDIDOS,
        CASE
            WHEN (EST.ESTOQUE - EST.RESERVADO - EST.WMSBLOQUEADO) <= 0 THEN 0
            ELSE LEAST(
                (EST.ESTOQUE - EST.RESERVADO - EST.WMSBLOQUEADO),
                GREATEST(NVL(WMS.SALDO_WMS_TELA, 0) - NVL(PED.QTD_PEDIDO_PENDENTE, 0), 0)
            )
        END AS DISPONIVEL_REAL_FINAL,
        (EST.ESTOQUE - NVL(WMS.SALDO_WMS_TELA, 0)) AS DIVERGENCIA_ERP_WMS
    FROM EstoqueComercial EST
    LEFT JOIN SaldoWmsTela WMS ON WMS.CODPROD = EST.CODPROD
    LEFT JOIN PedidosPendentes PED ON PED.CODPROD = EST.CODPROD
    LEFT JOIN TGFPRO PRO ON PRO.CODPROD = EST.CODPROD
    WHERE EST.ESTOQUE != NVL(WMS.SALDO_WMS_TELA, 0)
    ORDER BY ABS(EST.ESTOQUE - NVL(WMS.SALDO_WMS_TELA, 0)) DESC
)
WHERE ROWNUM <= 5000
