-- Pendencia de compras detalhada por ITEM
-- Query referencia para itens/produtos pendentes de entrega
-- Autor: Italo Gomes
-- Data: 2026-02-10
--
-- Uso:
--   Sem filtro: retorna TODOS os itens pendentes
--   Com filtro de marca: descomentar linha AND UPPER(MAR.DESCRICAO) = UPPER('TOME')
--   Com filtro de pedido: descomentar linha AND CAB.NUNOTA = 1168013
--
-- Regras de negocio MMarra:
--   CODTIPOPER 1301 = Compra Estoque
--   CODTIPOPER 1313 = Compra Casada (vinculada a venda/empenho)
--   CONFIRMADO = STATUSNOTA = 'L' (Liberado)
--   Comprador = TGFMAR.AD_CODVEND (comprador responsavel pela marca)
--   ITE.PENDENTE = 'S' exclui itens cancelados/cortados
--
-- ORDER BY prioridade: ATRASADO (0) > SEM PREVISAO (1) > PROXIMO (2) > NO PRAZO (3)

SELECT
    ITE.CODEMP AS COD_EMPRESA,
    EMP.NOMEFANTASIA AS NOME_EMPRESA,
    CAB.NUNOTA AS PEDIDO,
    CAB.CODTIPOPER,
    CASE
        WHEN CAB.CODTIPOPER = 1313 THEN 'Casada'
        WHEN CAB.CODTIPOPER = 1301 THEN 'Estoque'
    END AS TIPO_COMPRA,
    CAB.DTNEG AS DT_PEDIDO,
    CAB.DTPREVENT AS PREVISAO_ENTREGA,
    CASE
        WHEN CAB.STATUSNOTA = 'L' THEN 'Sim'
        ELSE 'Nao'
    END AS CONFIRMADO,
    PAR.CODPARC,
    PAR.NOMEPARC AS FORNECEDOR,
    MAR.AD_CODVEND AS COD_COMPRADOR,
    VEN.APELIDO AS COMPRADOR,
    PRO.CODPROD,
    PRO.DESCRPROD AS PRODUTO,
    MAR.CODIGO AS COD_MARCA,
    MAR.DESCRICAO AS MARCA,
    PRO.AD_NUMFABRICANTE AS NUM_FABRICANTE,
    PRO.AD_NUMORIGINAL AS NUM_ORIGINAL,
    ITE.CODVOL AS UNIDADE,
    ITE.QTDNEG AS QTD_PEDIDA,
    NVL(V_AGG.TOTAL_ATENDIDO, 0) AS QTD_ATENDIDA,
    (ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) AS QTD_PENDENTE,
    ITE.VLRUNIT AS VLR_UNITARIO,
    ITE.VLRTOT AS VLR_PEDIDO_ITEM,
    ROUND(NVL(V_AGG.TOTAL_ATENDIDO, 0) * ITE.VLRUNIT, 2) AS VLR_ATENDIDO,
    ROUND((ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) * ITE.VLRUNIT, 2) AS VLR_PENDENTE,
    TRUNC(SYSDATE) - TRUNC(CAB.DTNEG) AS DIAS_ABERTO,
    CASE
        WHEN CAB.DTPREVENT IS NULL THEN 'SEM PREVISAO'
        WHEN CAB.DTPREVENT < SYSDATE THEN 'ATRASADO'
        WHEN CAB.DTPREVENT < SYSDATE + 7 THEN 'PROXIMO'
        ELSE 'NO PRAZO'
    END AS STATUS_ENTREGA
FROM TGFITE ITE
JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
JOIN TSIEMP EMP ON EMP.CODEMP = ITE.CODEMP
JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
LEFT JOIN TGFMAR MAR ON MAR.CODIGO = PRO.CODMARCA
LEFT JOIN TGFVEN VEN ON VEN.CODVEND = MAR.AD_CODVEND
LEFT JOIN (
    SELECT V.NUNOTAORIG, V.SEQUENCIAORIG,
           SUM(V.QTDATENDIDA) AS TOTAL_ATENDIDO
    FROM TGFVAR V
    JOIN TGFCAB C ON C.NUNOTA = V.NUNOTA
    WHERE C.STATUSNOTA <> 'C'
    GROUP BY V.NUNOTAORIG, V.SEQUENCIAORIG
) V_AGG ON V_AGG.NUNOTAORIG = ITE.NUNOTA
       AND V_AGG.SEQUENCIAORIG = ITE.SEQUENCIA
WHERE CAB.CODTIPOPER IN (1301, 1313)
  AND CAB.STATUSNOTA <> 'C'
  AND CAB.PENDENTE = 'S'
  AND ITE.PENDENTE = 'S'
  --AND UPPER(MAR.DESCRICAO) = UPPER('TOME')            -- Filtro de marca
  AND (ITE.QTDNEG - NVL(V_AGG.TOTAL_ATENDIDO, 0)) > 0  -- Somente itens pendentes
  --AND CAB.NUNOTA = 1168013                             -- Filtro de pedido
ORDER BY
    CASE
        WHEN CAB.DTPREVENT IS NULL THEN 1
        WHEN CAB.DTPREVENT < SYSDATE THEN 0
        WHEN CAB.DTPREVENT < SYSDATE + 7 THEN 2
        ELSE 3
    END,
    MAR.DESCRICAO,
    PRO.DESCRPROD
